pypy: fix missing LDCXXSHARED in sysconfig.get_config_vars()
leading to a type error when compiling Pillow:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Co-authored-by: Sophie Tauchert <1221984+999eagle@users.noreply.github.com>